// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using drinking_be.Models;

#nullable disable

namespace drinking_be.Migrations
{
    [DbContext(typeof(DBDrinkContext))]
    [Migration("20251205125925_FinalPostgresDB")]
    partial class FinalPostgresDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("drinking_be.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company_name");

                    b.Property<string>("CopyrightText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("copyright_text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<string>("EmailSupport")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_support");

                    b.Property<string>("Hotline")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hotline");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slogan")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slogan");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tax_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__Brand__3213E83F3D8FA9ED");

                    b.ToTable("brand", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.Cart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Cart__3213E83FED0FE127");

                    b.HasIndex(new[] { "UserId" }, "UQ__Cart__B9BE370E2DCD722C")
                        .IsUnique();

                    b.ToTable("cart", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.CartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("base_price");

                    b.Property<long>("CartId")
                        .HasColumnType("bigint")
                        .HasColumnName("cart_id");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("final_price");

                    b.Property<short?>("IceLevelId")
                        .HasColumnType("smallint")
                        .HasColumnName("ice_level_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<long?>("ParentItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_item_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<short?>("SizeId")
                        .HasColumnType("smallint")
                        .HasColumnName("size_id");

                    b.Property<short?>("SugarLevelId")
                        .HasColumnType("smallint")
                        .HasColumnName("sugar_level_id");

                    b.HasKey("Id")
                        .HasName("PK__Cart_ite__3213E83F486E79A8");

                    b.HasIndex("CartId");

                    b.HasIndex("IceLevelId");

                    b.HasIndex("ParentItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.HasIndex("SugarLevelId");

                    b.ToTable("cart_item", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<byte?>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(NOW())");

                    b.HasKey("Id")
                        .HasName("PK__Category__3213E83F5A39BDEA");

                    b.HasIndex("ParentId");

                    b.HasIndex(new[] { "Slug" }, "UQ__Category__32DD1E4C00F59B8C")
                        .IsUnique();

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<int>("NewsId")
                        .HasColumnType("integer")
                        .HasColumnName("news_id");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Comment__3213E83FE8B13CD2");

                    b.HasIndex("NewsId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.IceLevel", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("label");

                    b.Property<short>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("PK__Ice_Leve__3213E83FD11018A5");

                    b.ToTable("ice_level", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.Membership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CardCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("card_code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<DateOnly?>("LastLevelSpentReset")
                        .HasColumnType("date")
                        .HasColumnName("last_level_spent_reset");

                    b.Property<DateOnly>("LevelEndDate")
                        .HasColumnType("date")
                        .HasColumnName("level_end_date");

                    b.Property<byte>("LevelId")
                        .HasColumnType("smallint")
                        .HasColumnName("level_id");

                    b.Property<DateOnly?>("LevelStartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("level_start_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalSpent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_spent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Membersh__3213E83FF483D767");

                    b.HasIndex("LevelId");

                    b.HasIndex(new[] { "CardCode" }, "UQ__Membersh__81703D727EAE3828")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "UQ__Membersh__B9BE370EFC41B82F")
                        .IsUnique();

                    b.ToTable("membership", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.MembershipLevel", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<byte>("Id"));

                    b.Property<string>("Benefits")
                        .HasColumnType("text")
                        .HasColumnName("benefits");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<short>("DurationDays")
                        .HasColumnType("smallint")
                        .HasColumnName("duration_days");

                    b.Property<decimal>("MinSpendRequired")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("min_spend_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Membersh__3213E83F3901FC68");

                    b.HasIndex(new[] { "Name" }, "UQ__Membersh__72E12F1BBCF20D34")
                        .IsUnique();

                    b.ToTable("membership_level", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<bool?>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_featured");

                    b.Property<Guid?>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("published_date");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("seo_description");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__News__3213E83F6A9F9780");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Slug" }, "UQ__News__32DD1E4C5A174899")
                        .IsUnique();

                    b.HasIndex(new[] { "PublicId" }, "UQ__News__5699A53062598161")
                        .IsUnique();

                    b.ToTable("news");
                });

            modelBuilder.Entity("drinking_be.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("CoinsEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("coins_earned");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_phone");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delivery_address");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("delivery_date");

                    b.Property<decimal?>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("grand_total");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_code");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("order_date")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_method_id");

                    b.Property<decimal?>("ShippingFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(8, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("shipping_fee");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.Property<string>("StoreName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("store_name");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_amount");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("UserNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_notes");

                    b.Property<string>("VoucherCodeUsed")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("voucher_code_used");

                    b.HasKey("Id")
                        .HasName("PK__Order__3213E83FDE5887F1");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "OrderCode" }, "UQ__Order__99D12D3FD8ECB07F")
                        .IsUnique();

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("base_price");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("final_price");

                    b.Property<short?>("IceLevelId")
                        .HasColumnType("smallint")
                        .HasColumnName("ice_level_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long?>("ParentItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_item_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<short?>("SizeId")
                        .HasColumnType("smallint")
                        .HasColumnName("size_id");

                    b.Property<short?>("SugarLevelId")
                        .HasColumnType("smallint")
                        .HasColumnName("sugar_level_id");

                    b.HasKey("Id")
                        .HasName("PK__Order_it__3213E83F36FD5A45");

                    b.HasIndex("IceLevelId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ParentItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.HasIndex("SugarLevelId");

                    b.ToTable("order_item", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<decimal?>("ProcessingFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("processing_fee");

                    b.Property<byte?>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("PK__Payment___3213E83F7896F946");

                    b.ToTable("payment_method", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(NOW())");

                    b.HasKey("Id")
                        .HasName("PK__Policy__3213E83FB49E512D");

                    b.HasIndex("BrandId");

                    b.HasIndex(new[] { "Slug" }, "UQ__Policy__32DD1E4C980885E3")
                        .IsUnique();

                    b.ToTable("policy", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("base_price");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Ingredient")
                        .HasColumnType("text")
                        .HasColumnName("ingredient");

                    b.Property<DateTime?>("LaunchDateTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("launch_date_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("product_type");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("public_id");

                    b.Property<byte[]>("SearchVector")
                        .HasColumnType("bytea")
                        .HasColumnName("search_vector");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<double?>("TotalRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("total_rating");

                    b.Property<int?>("TotalSold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_sold");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK__Product__3213E83F0F2383EA");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "Slug" }, "UQ__Product__32DD1E4CAB867B39")
                        .IsUnique();

                    b.HasIndex(new[] { "PublicId" }, "UQ__Product__5699A530AE3E7BDD")
                        .IsUnique();

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.ProductIceLevel", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<short>("IceLevelId")
                        .HasColumnType("smallint");

                    b.HasKey("ProductId", "IceLevelId");

                    b.HasIndex("IceLevelId");

                    b.ToTable("producticelevels");
                });

            modelBuilder.Entity("drinking_be.Models.ProductSize", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<short>("SizeId")
                        .HasColumnType("smallint");

                    b.HasKey("ProductId", "SizeId");

                    b.HasIndex("SizeId");

                    b.ToTable("productsizes");
                });

            modelBuilder.Entity("drinking_be.Models.ProductSugarLevel", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<short>("SugarLevelId")
                        .HasColumnType("smallint");

                    b.HasKey("ProductId", "SugarLevelId");

                    b.HasIndex("SugarLevelId");

                    b.ToTable("productsugarlevels");
                });

            modelBuilder.Entity("drinking_be.Models.Reservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AssignedTableId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_table_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_phone");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDepositPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<byte>("NumberOfGuests")
                        .HasColumnType("smallint")
                        .HasColumnName("number_of_guests");

                    b.Property<string>("ReservationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reservation_code");

                    b.Property<DateTime>("ReservationDatetime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reservation_datetime");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Reservat__3213E83F5F2BFAAF");

                    b.HasIndex("AssignedTableId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ReservationCode" }, "UQ__Reservat__FA8FADE431DEB25F")
                        .IsUnique();

                    b.ToTable("reservation", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasColumnType("text")
                        .HasColumnName("admin_response");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("media_url");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<byte>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Review__3213E83F5E4BD5F0");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("review", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.ShopTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("CanBeMerged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("can_be_merged");

                    b.Property<byte>("Capacity")
                        .HasColumnType("smallint")
                        .HasColumnName("capacity");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("MergedWithTableId")
                        .HasColumnType("integer")
                        .HasColumnName("merged_with_table_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.HasKey("Id")
                        .HasName("PK__Table__3213E83FCBCE513F");

                    b.HasIndex("MergedWithTableId");

                    b.HasIndex("StoreId");

                    b.ToTable("shop_table", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.Size", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("label");

                    b.Property<decimal?>("PriceModifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("price_modifier");

                    b.HasKey("Id")
                        .HasName("PK__Size__3213E83F985D1A04");

                    b.ToTable("size", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.SocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("platform_name");

                    b.Property<byte?>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("social_media");
                });

            modelBuilder.Entity("drinking_be.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<TimeSpan?>("CloseTime")
                        .HasColumnType("interval")
                        .HasColumnName("close_time");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<bool?>("MapVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("map_verified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<TimeSpan?>("OpenTime")
                        .HasColumnType("interval")
                        .HasColumnName("open_time");

                    b.Property<Guid?>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<byte?>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("PK__Store__3213E83FCF8EAB0E");

                    b.HasIndex("BrandId");

                    b.HasIndex(new[] { "Slug" }, "UQ__Store__32DD1E4C92725A74")
                        .IsUnique();

                    b.HasIndex(new[] { "PublicId" }, "UQ__Store__5699A53072383001")
                        .IsUnique();

                    b.ToTable("store", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.SugarLevel", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("label");

                    b.Property<short>("Value")
                        .HasColumnType("smallint")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("PK__Sugar_Le__3213E83F86537186");

                    b.ToTable("sugar_level", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<int?>("CurrentCoins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_coins");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool?>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid?>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<byte>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("role_id");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__User__3213E83F0D985B4B");

                    b.HasIndex(new[] { "PublicId" }, "UQ__User__5699A530AE2F5693")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E616418E7B215")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("full_address");

                    b.Property<bool?>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__User_Add__3213E83FE51862F8");

                    b.HasIndex("UserId");

                    b.ToTable("user_address", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.UserVoucher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiry_date");

                    b.Property<DateTime?>("IssuedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("issued_date")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<long?>("OrderIdUsed")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id_used");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UsedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("used_date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("voucher_code");

                    b.Property<int>("VoucherTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("voucher_template_id");

                    b.HasKey("Id")
                        .HasName("PK__User_Vou__3213E83F950C18C0");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherTemplateId");

                    b.HasIndex(new[] { "VoucherCode" }, "UQ__User_Vou__21731069F90ADEF0")
                        .IsUnique();

                    b.ToTable("user_voucher", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.VoucherTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CouponCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("coupon_code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("discount_value");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<byte?>("LevelId")
                        .HasColumnType("smallint")
                        .HasColumnName("level_id");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("max_discount_amount");

                    b.Property<decimal?>("MinOrderValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("min_order_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<byte?>("QuantityPerLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity_per_level");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("integer")
                        .HasColumnName("usage_limit");

                    b.Property<byte?>("UsageLimitPerUser")
                        .HasColumnType("smallint")
                        .HasColumnName("usage_limit_per_user");

                    b.Property<int?>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("used_count");

                    b.HasKey("Id")
                        .HasName("PK__Voucher___3213E83F0298D293");

                    b.HasIndex("LevelId");

                    b.HasIndex(new[] { "CouponCode" }, "UQ__Voucher___ADE5CBB794CB76DB")
                        .IsUnique();

                    b.ToTable("voucher_template", (string)null);
                });

            modelBuilder.Entity("drinking_be.Models.Cart", b =>
                {
                    b.HasOne("drinking_be.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("drinking_be.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Cart__user_id__37703C52");

                    b.Navigation("User");
                });

            modelBuilder.Entity("drinking_be.Models.CartItem", b =>
                {
                    b.HasOne("drinking_be.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart_item__cart___3B40CD36");

                    b.HasOne("drinking_be.Models.IceLevel", "IceLevel")
                        .WithMany("CartItems")
                        .HasForeignKey("IceLevelId")
                        .HasConstraintName("FK__Cart_item__ice_l__40058253");

                    b.HasOne("drinking_be.Models.CartItem", "ParentItem")
                        .WithMany("InverseParentItem")
                        .HasForeignKey("ParentItemId")
                        .HasConstraintName("FK__Cart_item__paren__3D2915A8");

                    b.HasOne("drinking_be.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Cart_item__produ__3C34F16F");

                    b.HasOne("drinking_be.Models.Size", "Size")
                        .WithMany("CartItems")
                        .HasForeignKey("SizeId")
                        .HasConstraintName("FK__Cart_item__size___3E1D39E1");

                    b.HasOne("drinking_be.Models.SugarLevel", "SugarLevel")
                        .WithMany("CartItems")
                        .HasForeignKey("SugarLevelId")
                        .HasConstraintName("FK__Cart_item__sugar__3F115E1A");

                    b.Navigation("Cart");

                    b.Navigation("IceLevel");

                    b.Navigation("ParentItem");

                    b.Navigation("Product");

                    b.Navigation("Size");

                    b.Navigation("SugarLevel");
                });

            modelBuilder.Entity("drinking_be.Models.Category", b =>
                {
                    b.HasOne("drinking_be.Models.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__Category__parent__3C69FB99");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("drinking_be.Models.Comment", b =>
                {
                    b.HasOne("drinking_be.Models.News", "News")
                        .WithMany("Comments")
                        .HasForeignKey("NewsId")
                        .IsRequired()
                        .HasConstraintName("FK__Comment__news_id__06CD04F7");

                    b.HasOne("drinking_be.Models.Comment", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK__Comment__parent___04E4BC85");

                    b.HasOne("drinking_be.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Comment__user_id__05D8E0BE");

                    b.Navigation("News");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("drinking_be.Models.Membership", b =>
                {
                    b.HasOne("drinking_be.Models.MembershipLevel", "Level")
                        .WithMany("Memberships")
                        .HasForeignKey("LevelId")
                        .IsRequired()
                        .HasConstraintName("FK__Membershi__level__51300E55");

                    b.HasOne("drinking_be.Models.User", "User")
                        .WithOne("Membership")
                        .HasForeignKey("drinking_be.Models.Membership", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Membershi__user___503BEA1C");

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("drinking_be.Models.News", b =>
                {
                    b.HasOne("drinking_be.Models.User", "User")
                        .WithMany("News")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__News__user_id__73BA3083");

                    b.Navigation("User");
                });

            modelBuilder.Entity("drinking_be.Models.Order", b =>
                {
                    b.HasOne("drinking_be.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodId")
                        .HasConstraintName("FK__Order__payment_m__29221CFB");

                    b.HasOne("drinking_be.Models.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK__Order__store_id__282DF8C2");

                    b.HasOne("drinking_be.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Order__user_id__2739D489");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("drinking_be.Models.OrderItem", b =>
                {
                    b.HasOne("drinking_be.Models.IceLevel", "IceLevel")
                        .WithMany("OrderItems")
                        .HasForeignKey("IceLevelId")
                        .HasConstraintName("FK__Order_ite__ice_l__31B762FC");

                    b.HasOne("drinking_be.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Order_ite__order__2CF2ADDF");

                    b.HasOne("drinking_be.Models.OrderItem", "ParentItem")
                        .WithMany("InverseParentItem")
                        .HasForeignKey("ParentItemId")
                        .HasConstraintName("FK__Order_ite__paren__2EDAF651");

                    b.HasOne("drinking_be.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Order_ite__produ__2DE6D218");

                    b.HasOne("drinking_be.Models.Size", "Size")
                        .WithMany("OrderItems")
                        .HasForeignKey("SizeId")
                        .HasConstraintName("FK__Order_ite__size___2FCF1A8A");

                    b.HasOne("drinking_be.Models.SugarLevel", "SugarLevel")
                        .WithMany("OrderItems")
                        .HasForeignKey("SugarLevelId")
                        .HasConstraintName("FK__Order_ite__sugar__30C33EC3");

                    b.Navigation("IceLevel");

                    b.Navigation("Order");

                    b.Navigation("ParentItem");

                    b.Navigation("Product");

                    b.Navigation("Size");

                    b.Navigation("SugarLevel");
                });

            modelBuilder.Entity("drinking_be.Models.Policy", b =>
                {
                    b.HasOne("drinking_be.Models.Brand", "Brand")
                        .WithMany("Policies")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK__Policy__brand_id__5BE2A6F2");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("drinking_be.Models.Product", b =>
                {
                    b.HasOne("drinking_be.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Product__updated__440B1D61");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("drinking_be.Models.ProductIceLevel", b =>
                {
                    b.HasOne("drinking_be.Models.IceLevel", "IceLevel")
                        .WithMany("ProductIceLevels")
                        .HasForeignKey("IceLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("drinking_be.Models.Product", "Product")
                        .WithMany("ProductIceLevels")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IceLevel");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("drinking_be.Models.ProductSize", b =>
                {
                    b.HasOne("drinking_be.Models.Product", "Product")
                        .WithMany("ProductSizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("drinking_be.Models.Size", "Size")
                        .WithMany("ProductSizes")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("drinking_be.Models.ProductSugarLevel", b =>
                {
                    b.HasOne("drinking_be.Models.Product", "Product")
                        .WithMany("ProductSugarLevels")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("drinking_be.Models.SugarLevel", "SugarLevel")
                        .WithMany("ProductSugarLevels")
                        .HasForeignKey("SugarLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SugarLevel");
                });

            modelBuilder.Entity("drinking_be.Models.Reservation", b =>
                {
                    b.HasOne("drinking_be.Models.ShopTable", "AssignedTable")
                        .WithMany("Reservations")
                        .HasForeignKey("AssignedTableId")
                        .HasConstraintName("FK__Reservati__assig__17C286CF");

                    b.HasOne("drinking_be.Models.Store", "Store")
                        .WithMany("Reservations")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservati__store__16CE6296");

                    b.HasOne("drinking_be.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Reservati__user___15DA3E5D");

                    b.Navigation("AssignedTable");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("drinking_be.Models.Review", b =>
                {
                    b.HasOne("drinking_be.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__Review__product___7F2BE32F");

                    b.HasOne("drinking_be.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Review__user_id__00200768");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("drinking_be.Models.ShopTable", b =>
                {
                    b.HasOne("drinking_be.Models.ShopTable", "MergedWithTable")
                        .WithMany("InverseMergedWithTable")
                        .HasForeignKey("MergedWithTableId")
                        .HasConstraintName("FK__Table__merged_wi__0D44F85C");

                    b.HasOne("drinking_be.Models.Store", "Store")
                        .WithMany("ShopTables")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK__Table__store_id__0C50D423");

                    b.Navigation("MergedWithTable");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("drinking_be.Models.SocialMedia", b =>
                {
                    b.HasOne("drinking_be.Models.Brand", "Brand")
                        .WithMany("SocialMedia")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("drinking_be.Models.Store", b =>
                {
                    b.HasOne("drinking_be.Models.Brand", "Brand")
                        .WithMany("Stores")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK__Store__brand_id__5535A963");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("drinking_be.Models.UserAddress", b =>
                {
                    b.HasOne("drinking_be.Models.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__User_Addr__user___787EE5A0");

                    b.Navigation("User");
                });

            modelBuilder.Entity("drinking_be.Models.UserVoucher", b =>
                {
                    b.HasOne("drinking_be.Models.User", "User")
                        .WithMany("UserVouchers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__User_Vouc__order__65370702");

                    b.HasOne("drinking_be.Models.VoucherTemplate", "VoucherTemplate")
                        .WithMany("UserVouchers")
                        .HasForeignKey("VoucherTemplateId")
                        .IsRequired()
                        .HasConstraintName("FK__User_Vouc__vouch__662B2B3B");

                    b.Navigation("User");

                    b.Navigation("VoucherTemplate");
                });

            modelBuilder.Entity("drinking_be.Models.VoucherTemplate", b =>
                {
                    b.HasOne("drinking_be.Models.MembershipLevel", "Level")
                        .WithMany("VoucherTemplates")
                        .HasForeignKey("LevelId")
                        .HasConstraintName("FK__Voucher_T__level__5E8A0973");

                    b.Navigation("Level");
                });

            modelBuilder.Entity("drinking_be.Models.Brand", b =>
                {
                    b.Navigation("Policies");

                    b.Navigation("SocialMedia");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("drinking_be.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("drinking_be.Models.CartItem", b =>
                {
                    b.Navigation("InverseParentItem");
                });

            modelBuilder.Entity("drinking_be.Models.Category", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("drinking_be.Models.Comment", b =>
                {
                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("drinking_be.Models.IceLevel", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductIceLevels");
                });

            modelBuilder.Entity("drinking_be.Models.MembershipLevel", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("VoucherTemplates");
                });

            modelBuilder.Entity("drinking_be.Models.News", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("drinking_be.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("drinking_be.Models.OrderItem", b =>
                {
                    b.Navigation("InverseParentItem");
                });

            modelBuilder.Entity("drinking_be.Models.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("drinking_be.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductIceLevels");

                    b.Navigation("ProductSizes");

                    b.Navigation("ProductSugarLevels");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("drinking_be.Models.ShopTable", b =>
                {
                    b.Navigation("InverseMergedWithTable");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("drinking_be.Models.Size", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductSizes");
                });

            modelBuilder.Entity("drinking_be.Models.Store", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reservations");

                    b.Navigation("ShopTables");
                });

            modelBuilder.Entity("drinking_be.Models.SugarLevel", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductSugarLevels");
                });

            modelBuilder.Entity("drinking_be.Models.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Comments");

                    b.Navigation("Membership");

                    b.Navigation("News");

                    b.Navigation("Orders");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");

                    b.Navigation("UserAddresses");

                    b.Navigation("UserVouchers");
                });

            modelBuilder.Entity("drinking_be.Models.VoucherTemplate", b =>
                {
                    b.Navigation("UserVouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
